on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  healthcheck_deployed_software:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/url-health-check
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2
        with:
          # The action will fail if any URL reports either 4xx or 5xx status codes.
          url: https://hidden-spire-33552.herokuapp.com|https://hidden-spire-33552.herokuapp.com/health|https://hidden-spire-33552.herokuapp.com/version