name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: ls
        run: ls -l
      - name: jest unit/integration tests
        run: npm run test
      - name: build
        run: npm run build
      - name: cypress e2e tests
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-prod
          command: npm run test:e2e
          wait-on: 'http://localhost:5000'
        # If all previous steps succeed, deploy
      - name: deploy to heroku
        # https://github.com/AkhileshNS/heroku-deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hidden-spire-33552
          heroku_email: ${{secrets.EMAIL}}
          # https://github.com/AkhileshNS/heroku-deploy#health-check
          healthcheck: "https://hidden-spire-33552.herokuapp.com/health"
          checkstring: "Healthy!"
          # https://blog.heroku.com/releases-and-rollbacks#rollbacks
          # https://github.com/AkhileshNS/heroku-deploy#rollback-on-healthcheck-failure
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        # https://github.com/anothrNick/github-tag-action
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        # https://github.com/nektos/act for testing actions locally
        # Steps run sequentially, if we reach here we have successfully versioned and deployed
      - name: Slack Notification on successful version and deploy
        # https://github.com/marketplace/actions/slack-notify
        uses: rtCamp/action-slack-notify@v2
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Successfully bumped version and deployed :rocket:"
      - name: Slack Notification on failure
        uses: rtCamp/action-slack-notify@v2
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Pipeline has failed"
          STEPS: ${{ toJson(steps) }}
          SLACK_MESSAGE: ${{ $STEPS }}